### ISSUE TITLE
Could not find a suitable physical device!

### ISSUE THREAD

**Issue by vikaig** [FlamingEnt/cake#2]
> Enabled extensions: VK_KHR_surface VK_KHR_xlib_surface 
> ...created Vulkan instance
> ...created Vulkan surface
> ...found 2 Vulkan-capable device(s)
> Could not find a suitable physical device!

https://github.com/FlamingEnt/cake/blob/4eaf1d5a9158bc8272743e2a7db651bfdd8ef8b5/src/engine/ref_vk/vk_device.c#L75
I have 1 Intel GPU, if I change ```count == 1``` to ```1```, then everything works
In ```vulkaninfo```, my Intel GPU is duplicated, it Vulkan ICD  bug https://github.com/KhronosGroup/Vulkan-Loader/issues/124 , but other vulkan applications bypass this bug and work fine

**Comment by raynorpat** [comment]
You can force the device to be used by using the vk_device cvar when starting the engine - like so:
`.\cake +set vk_device 0`

In your case I assume 0 or 1 will work.

This will force it to use a GPU of your choosing instead of searching for the best out of the bunch, my guess is that other apps don't do a search for the best and always default to the first discrete GPU.

A proper fix would be at the loader level though, seems they haven't pushed that in just yet.
